import React from 'react'

const about = () => {
  return (
    <div>
      i am about
    </div>
  )
}

export default about

export const metadata = {
  title: "MyBook : about",
  description: "Generated by create next app",
};
