import React from "react";
import Script from "next/script";

const page = () => {
  return (
    <div>
      <Script>
        {`
            alert("hello")
        `}
      </Script>
      i am contact
    </div>
  );
};

export default page;

export const metadata = {
  title: "MyBook : contact",
  description: "Generated by create next app",
};
